from typing import Any

class PlironError(Exception): ...

class Context:
    def __enter__(self) -> Context: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> bool: ...
    def is_ir_empty(self) -> bool: ...
    def close(self) -> None: ...

class Operation:
    def op_name(self) -> str: ...
    def num_results(self) -> int: ...
    def num_operands(self) -> int: ...
    def num_regions(self) -> int: ...
    def print(self) -> str: ...
    def verify(self) -> None: ...
