//! Python bindings for [`::pliron::irbuild::rewriter`].
//!
//! - [`PyRewriter`] — a Rust-side dispatch struct (like the listener structs in
//!   [`super::listener`]): holds a `Py<PyAny>` and implements the Rust
//!   [`Rewriter`] trait (and, per the `Rewriter: Inserter` supertrait,
//!   [`Inserter`] — that half is generated by the shared macro in the sibling
//!   `inserter` module) by calling the same-named method on the wrapped Python
//!   object. Not a `#[pyclass]`; used where Rust entry points need a
//!   Python-implemented rewriter. Rewriter methods are **required effects**, so
//!   a missing/raising method is a hard failure (see
//!   `call_required` (in the `inserter` module)).
//! - [`PyIRRewriter`] — `pliron.irbuild.IRRewriter`, a `#[pyclass]` wrapping the
//!   native [`IRRewriter<PyRewriteListener>`]; every method delegates to the
//!   wrapped native rewriter. The full `Inserter` surface is shared with
//!   `pliron.irbuild.IRInserter` via the `delegating_inserter_pymethods` macro;
//!   the rewrite-specific methods are added in a second `#[pymethods]` block.
//!   The optional `listener` is any (duck-typed) Python object implementing the
//!   listener protocol — see [`super::listener`].
//!
//! Because `PyIRRewriter`'s Python method signatures match what [`PyRewriter`]
//! dispatches, an `IRRewriter` instance is itself a valid Python rewriter
//! object for [`PyRewriter`].
//!
//! `ScopedRewriter` is deliberately not exposed: its save/restore-on-drop
//! semantics do not map to Python object lifetimes.

use pyo3::prelude::*;

use std::{string::ToString, vec::Vec};

use ::pliron::{
    basic_block::BasicBlock,
    context::{Context, Ptr},
    identifier::Identifier,
    irbuild::{
        inserter::{BlockInsertionPoint, Inserter, OpInsertionPoint},
        rewriter::{IRRewriter, Rewriter},
    },
    operation::Operation,
    region::Region,
    r#type::TypeHandle,
    value::Value,
};

use super::{
    inserter::{
        PyBlockInsertionPoint, PyOpInsertionPoint, call_required, delegating_inserter_pymethods,
        impl_python_inserter,
    },
    listener::PyRewriteListener,
};
use crate::{
    basic_block::PyBasicBlock, operation::PyOperation, region::PyRegion, types::PyType,
    value::PyValue,
};

// ---------------------------------------------------------------------------
// PyRewriter — a Python object as a Rust `Rewriter`
// ---------------------------------------------------------------------------

/// A Python object as a Rust [`Rewriter`]. See the module docs for the
/// dispatch/failure semantics.
pub struct PyRewriter {
    obj: Py<PyAny>,
}

impl PyRewriter {
    /// Wrap a Python rewriter object.
    pub fn new(obj: Py<PyAny>) -> Self {
        Self { obj }
    }
}

// `Rewriter: Inserter`, so the dispatch struct needs both impls; the `Inserter`
// half is identical to `PyInserter`'s and generated by the shared macro.
impl_python_inserter!(PyRewriter);

impl Rewriter for PyRewriter {
    fn replace_operation(
        &mut self,
        _ctx: &mut Context,
        op: Ptr<Operation>,
        new_op: Ptr<Operation>,
    ) {
        call_required(
            &self.obj,
            "replace_operation",
            (PyOperation { ptr: op }, PyOperation { ptr: new_op }),
        );
    }

    fn replace_operation_with_values(
        &mut self,
        _ctx: &mut Context,
        op: Ptr<Operation>,
        new_values: Vec<Value>,
    ) {
        let values: Vec<PyValue> = new_values.into_iter().map(|val| PyValue { val }).collect();
        call_required(
            &self.obj,
            "replace_operation_with_values",
            (PyOperation { ptr: op }, values),
        );
    }

    fn replace_value_uses_with(&mut self, _ctx: &Context, old_value: Value, new_value: Value) {
        call_required(
            &self.obj,
            "replace_value_uses_with",
            (PyValue { val: old_value }, PyValue { val: new_value }),
        );
    }

    fn erase_operation(&mut self, _ctx: &mut Context, op: Ptr<Operation>) {
        call_required(&self.obj, "erase_operation", (PyOperation { ptr: op },));
    }

    fn erase_block(&mut self, _ctx: &mut Context, block: Ptr<BasicBlock>) {
        call_required(&self.obj, "erase_block", (PyBasicBlock { ptr: block },));
    }

    fn erase_region(&mut self, _ctx: &mut Context, region: Ptr<Region>) {
        call_required(&self.obj, "erase_region", (PyRegion { ptr: region },));
    }

    fn unlink_operation(&mut self, _ctx: &Context, op: Ptr<Operation>) {
        call_required(&self.obj, "unlink_operation", (PyOperation { ptr: op },));
    }

    fn unlink_block(&mut self, _ctx: &Context, block: Ptr<BasicBlock>) {
        call_required(&self.obj, "unlink_block", (PyBasicBlock { ptr: block },));
    }

    fn move_operation(&mut self, _ctx: &Context, op: Ptr<Operation>, new_point: OpInsertionPoint) {
        call_required(
            &self.obj,
            "move_operation",
            (
                PyOperation { ptr: op },
                PyOpInsertionPoint { inner: new_point },
            ),
        );
    }

    fn move_block(
        &mut self,
        _ctx: &Context,
        block: Ptr<BasicBlock>,
        new_point: BlockInsertionPoint,
    ) {
        call_required(
            &self.obj,
            "move_block",
            (
                PyBasicBlock { ptr: block },
                PyBlockInsertionPoint { inner: new_point },
            ),
        );
    }

    fn split_block(
        &mut self,
        _ctx: &mut Context,
        block: Ptr<BasicBlock>,
        position: OpInsertionPoint,
        new_block_label: Option<Identifier>,
    ) -> Ptr<BasicBlock> {
        let ret = call_required(
            &self.obj,
            "split_block",
            (
                PyBasicBlock { ptr: block },
                PyOpInsertionPoint { inner: position },
                new_block_label.map(|l| l.to_string()),
            ),
        );
        Python::with_gil(|py| {
            ret.extract::<PyRef<'_, PyBasicBlock>>(py)
                .expect("Python split_block() must return a BasicBlock")
                .ptr
        })
    }

    fn inline_region(
        &mut self,
        _ctx: &Context,
        src_region: Ptr<Region>,
        dest_insertion_point: BlockInsertionPoint,
    ) {
        call_required(
            &self.obj,
            "inline_region",
            (
                PyRegion { ptr: src_region },
                PyBlockInsertionPoint {
                    inner: dest_insertion_point,
                },
            ),
        );
    }

    fn set_value_type(&mut self, _ctx: &Context, value: Value, new_type: TypeHandle) {
        call_required(
            &self.obj,
            "set_value_type",
            (PyValue { val: value }, PyType { ptr: new_type }),
        );
    }

    fn is_modified(&self) -> bool {
        let ret = call_required(&self.obj, "is_modified", ());
        Python::with_gil(|py| {
            ret.extract::<bool>(py)
                .expect("Python is_modified() must return a bool")
        })
    }

    fn mark_modified(&mut self) {
        call_required(&self.obj, "mark_modified", ());
    }
}

/// `pliron.irbuild.IRRewriter`: the native [`IRRewriter`] whose (optional)
/// listener is a duck-typed Python object.
#[pyclass(unsendable, name = "IRRewriter")]
pub struct PyIRRewriter {
    pub(crate) inner: IRRewriter<PyRewriteListener>,
    /// The Python listener object, retained so it can be read back. The *live*
    /// listener (a [`PyRewriteListener`] wrapping this same object) lives inside
    /// `inner` — this is a shared handle, not a copy.
    pub(crate) listener_obj: Option<Py<PyAny>>,
}

// The `Inserter` surface (append/insert/create_block/insertion points/
// is_modified/listener) — shared with `PyIRInserter`.
delegating_inserter_pymethods!(PyIRRewriter, PyRewriteListener);

#[pymethods]
impl PyIRRewriter {
    /// Create a rewriter, optionally at `insertion_point` and with a duck-typed
    /// Python `listener` (any object with `notify_*` hooks).
    #[new]
    #[pyo3(signature = (insertion_point=None, listener=None))]
    fn new(
        py: Python<'_>,
        insertion_point: Option<PyRef<'_, PyOpInsertionPoint>>,
        listener: Option<Py<PyAny>>,
    ) -> Self {
        let mut inner = IRRewriter::<PyRewriteListener>::default();
        if let Some(point) = insertion_point {
            inner.set_insertion_point(point.inner);
        }
        if let Some(obj) = &listener {
            inner.set_listener(PyRewriteListener::new(obj.clone_ref(py)));
        }
        PyIRRewriter {
            inner,
            listener_obj: listener,
        }
    }

    /// Replace `op` (erasing it) with `new_op`; result counts must match.
    fn replace_operation(&mut self, op: &PyOperation, new_op: &PyOperation) -> PyResult<()> {
        let ctx = crate::get_ctx_mut()?;
        self.inner.replace_operation(ctx, op.ptr, new_op.ptr);
        Ok(())
    }

    /// Replace `op` (erasing it) with `new_values`; counts must match results.
    fn replace_operation_with_values(
        &mut self,
        op: &PyOperation,
        new_values: Vec<PyRef<'_, PyValue>>,
    ) -> PyResult<()> {
        let values: Vec<Value> = new_values.iter().map(|v| v.val).collect();
        let ctx = crate::get_ctx_mut()?;
        self.inner
            .replace_operation_with_values(ctx, op.ptr, values);
        Ok(())
    }

    /// Replace all uses of `old_value` with `new_value`.
    fn replace_value_uses_with(
        &mut self,
        old_value: &PyValue,
        new_value: &PyValue,
    ) -> PyResult<()> {
        let ctx = crate::get_ctx()?;
        self.inner
            .replace_value_uses_with(ctx, old_value.val, new_value.val);
        Ok(())
    }

    /// Erase `op` (and its regions). The op must have no uses.
    fn erase_operation(&mut self, op: &PyOperation) -> PyResult<()> {
        let ctx = crate::get_ctx_mut()?;
        self.inner.erase_operation(ctx, op.ptr);
        Ok(())
    }

    /// Erase `block` (and its ops). The block must have no uses.
    fn erase_block(&mut self, block: &PyBasicBlock) -> PyResult<()> {
        let ctx = crate::get_ctx_mut()?;
        self.inner.erase_block(ctx, block.ptr);
        Ok(())
    }

    /// Erase `region` (and its blocks). Invalidates later regions' indices.
    fn erase_region(&mut self, region: &PyRegion) -> PyResult<()> {
        let ctx = crate::get_ctx_mut()?;
        self.inner.erase_region(ctx, region.ptr);
        Ok(())
    }

    /// Unlink `op` from its block (without erasing it).
    fn unlink_operation(&mut self, op: &PyOperation) -> PyResult<()> {
        let ctx = crate::get_ctx()?;
        self.inner.unlink_operation(ctx, op.ptr);
        Ok(())
    }

    /// Unlink `block` from its region (without erasing it).
    fn unlink_block(&mut self, block: &PyBasicBlock) -> PyResult<()> {
        let ctx = crate::get_ctx()?;
        self.inner.unlink_block(ctx, block.ptr);
        Ok(())
    }

    /// Move `op` to `new_point`.
    fn move_operation(&mut self, op: &PyOperation, new_point: &PyOpInsertionPoint) -> PyResult<()> {
        let ctx = crate::get_ctx()?;
        self.inner.move_operation(ctx, op.ptr, new_point.inner);
        Ok(())
    }

    /// Move `block` to `new_point`.
    fn move_block(
        &mut self,
        block: &PyBasicBlock,
        new_point: &PyBlockInsertionPoint,
    ) -> PyResult<()> {
        let ctx = crate::get_ctx()?;
        self.inner.move_block(ctx, block.ptr, new_point.inner);
        Ok(())
    }

    /// Split `block` at `position`, moving everything from there on into a new
    /// block (inserted right after); returns the new block.
    #[pyo3(signature = (block, position, new_block_label=None))]
    fn split_block(
        &mut self,
        block: &PyBasicBlock,
        position: &PyOpInsertionPoint,
        new_block_label: Option<&str>,
    ) -> PyResult<PyBasicBlock> {
        let label = new_block_label
            .map(|s| Identifier::try_from(s.to_string()))
            .transpose()
            .map_err(crate::to_py_err)?;
        let ctx = crate::get_ctx_mut()?;
        let ptr = self
            .inner
            .split_block(ctx, block.ptr, position.inner, label);
        Ok(PyBasicBlock { ptr })
    }

    /// Move all blocks of `src_region` to `dest_insertion_point`, leaving
    /// `src_region` empty. The caller fixes up control flow.
    fn inline_region(
        &mut self,
        src_region: &PyRegion,
        dest_insertion_point: &PyBlockInsertionPoint,
    ) -> PyResult<()> {
        let ctx = crate::get_ctx()?;
        self.inner
            .inline_region(ctx, src_region.ptr, dest_insertion_point.inner);
        Ok(())
    }

    /// Change the type of `value`. `new_type` may be a generic `Type` or any
    /// concrete type wrapper.
    fn set_value_type(&mut self, value: &PyValue, new_type: &Bound<'_, PyAny>) -> PyResult<()> {
        let handle = crate::types::type_handle_from_any(new_type)?;
        let ctx = crate::get_ctx()?;
        self.inner.set_value_type(ctx, value.val, handle);
        Ok(())
    }
}
